---
title: "Curriculum Vitae"
author: 
- name: "Anni Norring, Bank of Finland and University of Helsinki"
  affiliation: "anni.norring@bof.fi"
date: "2019"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_float: true
    toc_depth: 3
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. General information

I am currently an economist at the Bank of Finland and a PhD candidate in economics at the University of Helsinki. Ten years from now I will be a PhD in economics specialized in international macroeconomics with solid understanding of how economies work gained from working with a central bank or an international organization.

I am interested in anything that is hard to understand. I firmly believe there is nothing more exciting than learning something new, be it in the field of economics, programming, dancing ballet or renovating. I like to learn new things by reading, listening and trying out: I am never caught without a book (or two) in my bag, I try to keep my language skills up by listening to i.e. a french science podcast while walking to work and I never say no, when something interesting comes my way.


|Contact information|
|------|------------------------------------------------------------------------------------|
|Name|Anni Norring|
|Date of birth and place|26.7.1986, Espoo, Finland|
|Address|Sinebrychoffinkatu 15 a 24, 00120 Helsinki, Finland|
|Telephone|+358407443401|
|E-mail|anni.norring@helsinki.fi|
|LinkedIn|[linkedin.com/in/anninorring](https://www.linkedin.com/in/anninorring/)|
|Twitter|[twitter.com/AnniNorring](https://twitter.com/AnniNorring)|
|GitHub|[github.com/anorring](https://github.com/anorring)|
|||

|Language proficiency|
|------------------------|------------------------------------------------------------------------------------|
|Finnish|native fluency, full professional proficiency|
|English|fluent, full professional proficiency|
|Swedish|full proficiency, very good reading and writing skills, conversational ability|
|French|limited proficiecy, good reading and writing skills, basic conversational ability|
|German|limited proficiecy, basic reading and writing skills, limited conversational ability|
|Spanish|limited proficiecy, basic reading and writing skills, limited conversational ability|
|Italian|limited proficiecy, basic reading and writing skills, limited conversational ability|
|Latin|limited proficiecy, basic reading and writing skills|
|Studies also in|Russian, Japanese, Chinese, Danish (I've always had this thing for languages)|
|||

|Technical skills|
|------------------------|------------------------------------------------------------------------------------|
|Proficient with|Microsoft Office suite, R, Stata, Git, Lateχ, Matlab, Dynare, Macrobond, CEIC|
|Basic knowledge of|Tableau, IRIS, Python, Bloomberg, SPSS|
|||


# 2. What I do now: International economic policy & Research on macroprudential policy spillovers

**1/2019 - **  
**Economist at the Bank of Finland**
I work as an economist in the International Affairs division of the Bank of Finland. My responsibilities range from analysing the international economy to formulating Finnish positions in international economic policy. Particularly, in a team of a two economists, I am responsible for Finland's relations to the International Monetary Fund (IMF). In addition, I am responsible for affairs related to the Bank of International Settlements (BIS).

**9/2016 - 5/2020**  
**Doctor of Social Sciences in Economics**  
University of Helsinki, Faculty of Social Sciences  

In my thesis I apply the gravity model to international banking and specifically to studying the cross-border spillover effects of nationally implemented macroprudential policy via international lending.

In my course work I have tried to emphasize maintaining, updating and improving my methodological know-how. I have taken courses on e.g. open data science (R, open data sources, Git), DSGE models, Bayesian times series methods, different classes of VARs and Bayesian methods for DSGE models. 

I have been a doctoral student representative in the steering committee of the Doctoral Programme in Economics during the academic years 2017-2018 and 2018-2019.


# 3. Research

## 3.1 First paper of the thesis: "Macroprudential policy spillovers and international banking - Taking the gravity approach"

In this paper I study how the effects macroprudential policy spill across borders via international lending. For a set of 157 countries, I estimate a gravity model applied to international banking, where the use of different macroprudential policy measures enter as friction variables. My findings support the existence of cross-border spillovers from macroprudential policy. Moreover, I find that the overall effect from more macroprudential regulation is highly dependent on the income group of the countries in which banks operate: the effect is of opposite sign for advanced and for emerging economies. I argue that the differences may tell of banks having more opportunities for regulatory arbitrage in emerging market economies than in advanced economies.
 
These results should be in the interest of authorities responsible for macroprudential policy, because the knowledge on the cross-border spillovers from macroprudential policy and how this affects the actions of internationally active banks is still limited. For full understanding of the effectiveness and limitations of macroprudential policy measures the spillover effects should not be ignored. My results point to interesting differences between the potential spillover effects for countries from different income classes, emphasizing the need for a deeper understanding of the channels of effect at play. 

## 3.2 Second paper of the thesis: "Does macroprudential policy increase home bias in the Euro area? A dynamic gravity approach"



## 3.3 Third paper of the thesis: "Regulatory arbitrage in action? Spillovers from macroprudential policy in the major EMEs"



# 4. Education

## 4.1 Doctoral studies

**9/2016 - 5/2020**  
**Doctor of Social Sciences in Economics**  
University of Helsinki, Faculty of Social Sciences  

In my thesis I apply the gravity model to international banking and specifically to studying the cross-border spillover effects of nationally implemented macroprudential policy via international lending.

In my course work I have tried to emphasize maintaining, updating and improving my methodological know-how. I have taken courses on e.g. open data science (R, open data sources, Git), DSGE models, Bayesian times series methods, different classes of VARs and Bayesian methods for DSGE models. 

I have been a doctoral student representative in the steering committee of the Doctoral Programme in Economics during the academic years 2017-2018 and 2018-2019.

**Grants**

**3/2018** University of Helsinki travel grant  
**2/2018** Finnish Cultural Foundation three-year grant  
**12/2017** Yrj&ouml; Jahnsson Foundation grant (6 months)  
**6/2017** Oskar &Ouml;flunds Stiftelse grant (4 months)  
**12/2016** Yrj&ouml; Jahnsson Foundation grant (6 months)  
**5/2016** Yrj&ouml; Jahnsson Foundation grant for first year doctoral studies (12 months)  


## 4.2 Master's and Bachelor's studies

**9/2011 - 1/2015**  
**Master of Social Sciences in Economics**  
University of Helsinki, Faculty of Social Sciences.  
Major subject economics, minor subject mathematics and statistics. Overall GPA 4/5.  
Master's thesis topic: Cross-border investments, gravity equations and the double-hurdle model. Graded eximia cum laude approbatur (6/7).  
Bachelor's thesis topic: Macroeconomic effects of venture capitalism. Graded 5/5.  

I graduated as a master of social sciences from the University of Helsinki in January 2015 with economics as my major subject. During my studies I took a special interest in macroeconomics and tried to emphasize this in the courses I selected. I graduated as a bachelor of social sciences in May 2012. I have minored in statistics (GPA 4.0) and have mathematics as a second major (GPA 4.0).  

In my master’s thesis I proposed a previously untapped method, the double-hurdle model, for estimating the determinants of cross-border investments. My goal was to write a thesis with actual scientific relevance and I was proud to achieve this. My thesis was graded Eximia cum laude approbatur, or 6/7.  

In my bachelor's thesis I studied the possible macroeconomic effects of venture capitalism. I was able to publish an article based on my thesis at the Bank of Finland. My thesis was graded 5/5.  

**8/2006 - **  
**Master of Science in Mathematics**  
University of Helsinki, Faculty of Science.   
Major subject mathematics, minor subject economics and statistics. Overall GPA 4/5.  

I started as a mathematics student in the University of Helsinki, but my studies centered on economics at a fairly early stage. Studying mathematics has improved my analytic skills, which I have noticed to be endlessly valuable in working life.  

## 4.3 Other education

**5/2006**  
**It&auml;keskus Upper Secondary School, language program.**  
Matriculation examination in 9 subjects with an overall degree of eximia cum laude approbatur.

# 5. Professional experience

## 5.1 Bank of Finland

**1/2019 - **  
**Economist**
**Bank of Finland, European and International Affairs, General Secretariat**
I work as an economist in the International Affairs division of the Bank of Finland. My responsibilities range from analysing the international economy to formulating Finnish positions in international economic policy. Particularly, in a team of a two economists, I am responsible for Finland's relations to the International Monetary Fund (IMF). In addition, I am responsible for affairs related to the Bank of International Settlements (BIS).

**1/2018 - 3/2018**  
**Economist**  
**Bank of Finland, Financial Stability and Statistics, Division of Macroprudential Policy**  
I worked with issues related to macroprudential policy, financial stability and prudential regulation. My work consisted of writing analysis for internal reports and Bank of Finland publications, giving presentations, preparing policy briefs and comments for various high-level meetings and participating in seminars and conferences. I also conducted my own research on the effects of macroprudential instruments on bilateral cross-border bank asset holdings, related to my PhD-thesis. 

Publications from this visit: a blog post, an analysis and an article for the Bank of Finland Bulletin -site:

[Kauko, Karlo; Norring, Anni (2018). "Instruments designed to mitigate indebtedness" A Bank of Finland Bulletin article.](https://www.bofbulletin.fi/en/2018/2/instruments-designed-to-mitigate-indebtedness/)

[Kauko, Karlo; Norring, Anni (2018). "Velkaantumista rajoittavat välineet" A Bank of Finland Bulletin article, in Finnish.](https://www.eurojatalous.fi/fi/2018/2/velkaantumista-rajoittavat-valineet/)

[Norring, Anni (2018). "Makrovakauspolitiikka vakiintuu Euroopan unionissa" A Bank of Finland Bulletin analysis article, in Finnish.](https://www.eurojatalous.fi/fi/2018/artikkelit/makrovakauspolitiikka-vakiintuu-euroopan-unionissa/)

[Norring, Anni (2018). "Mistä puhumme, kun puhumme makrovakauspolitiikasta?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2018/mista-puhumme-kun-puhumme-makrovakauspolitiikasta/)

**5/2017 - 9/2017**  
**Economist**  
**Bank of Finland, Financial Stability and Statistics, Division of Macroprudential Policy**  
My work mainly consisted of conducting my own research on monetary and macroprudential policy in the presence of a global financial cycle. I also wrote analysis on e.g. the financial stability spillovers from China, prepared briefs for various high-level meeting and participated in seminars and conferences. Two of my analysis were published in the Bank of Finland blog (in Finnish). I was also asked to write a piece on China and financial stability spillovers in Kauppalehti, a Finnish business newspaper. An enjoyable side project was participating in a summer innovation competition, which I won with my proposal for developing the way the Bank of Finland and the Financial Supervisory Authority engage with the younger generations.  

Publications from this visit: two blog posts and a piece in Kauppalehti:

[Norring, Anni (2017). "Makrovakauspolitiikka globaalia finanssisykliä kesyttämässä". A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2017/makrovakauspolitiikka-globaalia-finanssisyklia-kesyttamassa/)

[Norring, Anni (2017). "Debatti: Kiinan markkinahäiriöt voivat heiluttaa maailmanmarkkinoita". Article in Kauppalehti, 28.8.2017.](https://www.kauppalehti.fi/uutiset/debatti-kiinan-markkinahairiotvoivat-heiluttaa-maailmanmarkkinoita/XEu5GsJk)

[Norring, Anni (2017). "Kuinka paljon Kiina vaikuttaa kansainvälisiin rahoitusmarkkinoihin?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2017/kuinka-paljon-kiina-vaikuttaa-kansainvalisiin-rahoitusmarkkinoihin/)

**10/2014 - 2/2016**  
**Economist, China**  
**Bank of Finland Institute for Economies in Transition (BOFIT)**  
I was part of a team of three economists that follows and analyzes the Chinese economy at the Bank of Finland Institute for Economies in Transition or BOFIT. My responsibilities included e.g. writing weekly about the most important economic events in China to the [BOFIT Weekly](https://www.bofit.fi/en/monitoring/weekly/), which contains timely analysis and news about the Russian and Chinese economy. Besides the BOFIT Weekly, I wrote ad-hoc analysis for internal use and for publications such us our [BOFIT Policy Brief -series](https://helda.helsinki.fi/bof/handle/123456789/25/browse?type=author&value=Norring%2C+Anni) and [Bank of Finland blog](https://www.eurojatalous.fi/fi/kirjoittaja/anni-norring/).  

Communicating our view on the Chinese economy to the media and other interest groups as well as networking with other China experts was also an important part of the job, as was taking part in various seminars, conferences and workshops. My work was mainly policy work, but as academic work is also an integral part of BOFIT, I did eg. have the opportunity of being a discussant at Asian Economic Panel 2015 at the Lund University in Sweden. My comments were published in [MIT Press Journal Asian Economic Papers (Summer 2016, Vol. 15, No. 2 , Pages 134-135)](https://www.mitpressjournals.org/doi/full/10.1162/ASEP_a_00433).  

In addition to my responsibilities at BOFIT, I organized two types of seminars. The first one is open to the whole personnel and held on average twice a month. In this series experts at Bank of Finland and Financial Supervision Authority give presentations on interesting and topical themes. The other is a summer seminar open for summer trainees and organized once a week during the summer months.  

I tried to keep my ability to give a presentation about something else than economics alive by occasionally presenting the art collection of the Bank of Finland for different kinds of visitors. When talking about e.g. the Chinese economy, you can up to a degree anticipate the questions asked. With the guided art tours, you have no idea what the visitors may come up with.  

Publications related to this position: 

[Norring, Anni (2016). “Comments by Anni Norring, on The Impact of CEO Long-term Equity-based Compensation Incentives on Economic Growth in Collectivist versus Individualist Countries”. MIT Press Journal Asian Economic Papers, Summer 2016, Vol. 15, No. 2, Pages 134-135.](https://www.mitpressjournals.org/doi/full/10.1162/ASEP_a_00433)

[Rautava, Jouko; Nuutilainen, Riikka; Norring, Anni; Korhonen, Iikka; Kallio, Jyrki (2015). ”BOFIT Kiina-tietoisku 2015”. BOFIT Policy Brief 11/2015](http://urn.fi/URN:NBN:fi:bof-201601071001)

[Norring, Anni (2015). ”Suomen ja Venäjän välisten suorien sijoitusten tilastot”. BOFIT Policy Brief 6/2015.](http://urn.fi/URN:NBN:fi:bof-201506301310)

[Norring, Anni (2015). "Juanin kurssi määräytyy jatkossa enemmän markkinoilla". A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2015-2/juanin-kurssi-maaraytyy-jatkossa-enemman-markkinoilla/)

[Norring, Anni (2015). "Kiinan pörssikurssit menevät ylös ja alas, vaikuttaako se mihinkään?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2015-2/kiinan-porssikurssit-menevat-ylos-ja-alas--vaikuttaako-se-mihinkaan/)


**1/2014 - 10/2014**  
**Economist intern**  
**Bank of Finland, Financial Stability and Statistics, Division of Statistical analysis**  
My responsibilities included e.g. developing a new compiling process for insurance company and pension fund statistics, and publishing and presenting investment fund statistics. I also mapped and drafted illustrations of all the different work processes of the statistics compiled and published by the statistics department of the Bank of Finland, as this had not been done before.  

During summer 2014 I thought up and organized a seminar for summer trainees, in which economists and other experts of the Bank of Finland gave presentations on different topics related to their field of work. The seminar provided opportunities of discussion on a multitude of subjects and made the functions of the central bank more familiar for the trainees. The seminar was received well by trainees and presenters alike and will in the coming years be included in the schedule of summer trainees.

**4/2011 - 12/2013**  
**Economist intern**  
**Bank of Finland, Financial Stability and Statistics, Division of Balance of Payments**  
The most extensive project I did was a methodological project aimed at improving the quality of balance of payments statistics by reducing the balancing item of the statistical framework. On the account of this work I wrote an article ["Maksutaseen tunnistamattomat ja virheelliset erät"](http://urn.fi/URN:NBN:fi:bof-20140807733), which was published in the Bank of Finland BoF Online -series.  

My other responsibilities included e.g. compiling and publishing the balance of payments statistics and streamlining the process of the monthly online publication. I also had the opportunity to write an article based on my bachelor's thesis and published in the [Financial Market Report of Bank of Finland](http://urn.fi/URN:NBN:fi:bof-201408075204). 

## 5.2 Other

**10/1998 - 3/2011**  
**Financial administrative assistant, assistant**  
**Moskito Group Oy, previously Varesvuo Partners Oy**  
I gained experience in financial administration at Moskito Group Oy, which is the parent company of a concern consisting of media, advertising and TV-production companies. In Moskito Group I worked for several years as an accounting and office assistant after school and during school holidays.  

I started in the company as a young girl (prior to getting paid for real since I was twelve, I was paid in cute stationary), helping out in the office during school holidays and gaining more responsibility as my experience increased. For the last two years there I was responsible for the management of purchase invoices for almost the entire concern.  

The most valuable experience from Moskito was the opportunity to gain work experience at a very young age and the ability to organize my work very independently. 


# 6. Conference and seminar presentations, lectures and teaching  

## 6.1 Conference and seminar presentations

**5/2019** Presenting "Macroprudential policy spillovers and international banking - Taking the gravity approach", Financial Engineering and Banking Society 9th International Conference, Prague, Czech Republic

**5/2019** Discussant in a session on Financial stability, Financial Engineering and Banking Society 9th International Conference, Prague, Czech Republic

**5/2019** Presenting "Macroprudential policy spillovers and international banking - Taking the gravity approach", RiskLab/BoF/ESRB Conference on Systemic Risk Analytics, Helsinki, Finland

**3/2019** Presenting "Macroprudential policy spillovers and international banking - Taking the gravity approach", Bank of Finland internal research seminar, Helsinki, Finland

**5/2018** Presenting "Macroprudential policy cross-border spillovers and international banking - Any use for the gravity model?", HECER Research Workshop on Macroeconomics, Helsinki, Finland

**5/2018** Presenting "Macroprudential policy cross-border spillovers and international banking - Any use for the gravity model?", Bank of Finland internal seminar, Helsinki, Finland

**2/2017** Discussant in a session on the Chinese economy, Finnish Economic Association XXXIX Annual Meeting, Jyv&auml;skyl&auml; University, Finland  


## 6.2 Teaching and lectures

**3/2019** Teacher, two lectures in a course on the Chinese economy, University of Turku, Finland

**11-12/2018** Teacher (exercises) for master's course "Macroeconomics II: Business cycles"", University of Helsinki, Finland

**9-10/2018** Teacher (exercises) for master's course "Macroeconomics I: Economic growth" , University of Helsinki, Finland

**8/2018** Teacher, lecture course on international macroeconomics, University of Helsinki, Finland

**3/2018** Lecture on the Chinese economy, University of the Third Age, Imatra, Finland  

**10-11/2017** Teacher (exercises) for master's course "Macroeconomics II: Business cycles"", University of Helsinki, Finland



# 7. Publications, writings and media

## 7.1 Research papers

### 7.1.1 First paper of the thesis: "Macroprudential policy spillovers and international banking - Taking the gravity approach"

In this paper I study how the effects macroprudential policy spill across borders via international lending. For a set of 157 countries, I estimate a gravity model applied to international banking, where the use of different macroprudential policy measures enter as friction variables. My findings support the existence of cross-border spillovers from macroprudential policy. Moreover, I find that the overall effect from more macroprudential regulation is highly dependent on the income group of the countries in which banks operate: the effect is of opposite sign for advanced and for emerging economies. I argue that the differences may tell of banks having more opportunities for regulatory arbitrage in emerging market economies than in advanced economies.
 
These results should be in the interest of authorities responsible for macroprudential policy, because the knowledge on the cross-border spillovers from macroprudential policy and how this affects the actions of internationally active banks is still limited. For full understanding of the effectiveness and limitations of macroprudential policy measures the spillover effects should not be ignored. My results point to interesting differences between the potential spillover effects for countries from different income classes, emphasizing the need for a deeper understanding of the channels of effect at play. 

### 7.1.2 Second paper of the thesis: "Does macroprudential policy increase home bias in the Euro area? A dynamic gravity approach"

### 7.1.3 Third paper of the thesis: "Regulatory arbitrage in action? Spillovers from macroprudential policy in the major EMEs"

## 7.2 Publications for professional communities

[Norring, Anni (2016). “Comments by Anni Norring, on The Impact of CEO Long-term Equity-based Compensation Incentives on Economic Growth in Collectivist versus Individualist Countries”. MIT Press Journal Asian Economic Papers, Summer 2016, Vol. 15, No. 2, Pages 134-135.](https://www.mitpressjournals.org/doi/full/10.1162/ASEP_a_00433)

[Rautava, Jouko; Nuutilainen, Riikka; Norring, Anni; Korhonen, Iikka; Kallio, Jyrki (2015). ”BOFIT Kiina-tietoisku 2015”. BOFIT Policy Brief 11/2015](http://urn.fi/URN:NBN:fi:bof-201601071001)

[Norring, Anni (2015). ”Suomen ja Venäjän välisten suorien sijoitusten tilastot”. BOFIT Policy Brief 6/2015.](http://urn.fi/URN:NBN:fi:bof-201506301310)


## 7.3 Publications for the general public, such as analyses, articles and blogs

[Kauko, Karlo; Norring, Anni (2018). "Instruments designed to mitigate indebtedness" A Bank of Finland Bulletin article.](https://www.bofbulletin.fi/en/2018/2/instruments-designed-to-mitigate-indebtedness/)

[Kauko, Karlo; Norring, Anni (2018). "Velkaantumista rajoittavat välineet" A Bank of Finland Bulletin article, in Finnish.](https://www.eurojatalous.fi/fi/2018/2/velkaantumista-rajoittavat-valineet/)

[Norring, Anni (2018). "Makrovakauspolitiikka vakiintuu Euroopan unionissa" A Bank of Finland Bulletin analysis article, in Finnish.](https://www.eurojatalous.fi/fi/2018/artikkelit/makrovakauspolitiikka-vakiintuu-euroopan-unionissa/)

[Norring, Anni (2018). "Mistä puhumme, kun puhumme makrovakauspolitiikasta?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2018/mista-puhumme-kun-puhumme-makrovakauspolitiikasta/)

[Norring, Anni (2017). "Makrovakauspolitiikka globaalia finanssisykliä kesyttämässä". A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2017/makrovakauspolitiikka-globaalia-finanssisyklia-kesyttamassa/)

[Norring, Anni (2017). "Debatti: Kiinan markkinahäiriöt voivat heiluttaa maailmanmarkkinoita". Article in Kauppalehti, 28.8.2017.](https://www.kauppalehti.fi/uutiset/debatti-kiinan-markkinahairiotvoivat-heiluttaa-maailmanmarkkinoita/XEu5GsJk)

[Norring, Anni (2017). "Kuinka paljon Kiina vaikuttaa kansainvälisiin rahoitusmarkkinoihin?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2017/kuinka-paljon-kiina-vaikuttaa-kansainvalisiin-rahoitusmarkkinoihin/)

[Norring, Anni (2015). "Juanin kurssi määräytyy jatkossa enemmän markkinoilla". A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2015-2/juanin-kurssi-maaraytyy-jatkossa-enemman-markkinoilla/)

[Norring, Anni (2015). "Kiinan pörssikurssit menevät ylös ja alas, vaikuttaako se mihinkään?" A Bank of Finland Bulletin blog, in Finnish.](https://www.eurojatalous.fi/fi/blogit/2015-2/kiinan-porssikurssit-menevat-ylos-ja-alas--vaikuttaako-se-mihinkaan/)


## 7.4 Theses

[Norring, Anni (2015). ” Cross-border Investments, Gravity Equations and the Double-hurdle Model”. Master’s thesis.](https://helda.helsinki.fi/handle/10138/153567)

Norring, Anni (2011). “Riskirahoituksen merkitys kansantaloudelle”. Bachelor’s thesis. 


## 7.5 Media appearances

["Kiina devalvoi jo kolmatta päivää - Asiantuntija: Maa hakee uskottavuutta valuutalleen". Interview by Helsingin Sanomat, 13.8.2015.](https://www.hs.fi/talous/art-2000002844710.html)

["Kiina yllätti devalvaatiolla". Interview by Helsingin Sanomat, 12.8.2015.](https://www.hs.fi/talous/art-2000002844450.html)

# 8. Hobbies

## 8.1 Reading
I have been devouring books since I was a baby (quite literally, as my mother maintains). The family lore tells that I would not fall asleep without at least four books in my bed and that I learned to read when I was four because my parents simply could not read to me as much as I wanted. To this day, I never leave home without a book. Or two.

When I started school, I was given a notebook where I could write down the books I've read. I’ve managed to keep this habit up, meaning that I have data on my reading for most of my life. According to my notebooks I have read 1410 books so far. These days I read on average 50 books a year. The average has varied quite a lot. When I was in elementery school and reading through the kids' section at the local library in alphabetical order, I managed to go through a 100 books a year (which I considered a cool badge of honour). On the other hand, when I was 13 and decided that from there on, I would only read philosophy "as to educate my thinking" and could understand next to nothing from the various Kants and Wittgensteins, I was down to 20 books a year. That experiment lasted for three years, and I attribute my having any friends at all at school to a very cool and popular sister. 

These days my reading does not follow a manifesto or a programme. I simply read for pleasure, for learning, for living multiple lives, for visiting places, times and universes beyond my reach.


## 8.2 Investing
In 8th grade, I unexpectedly won a competition my school organized on economics. As the first price I received a small share in a mutual fund. That share ended up being one of my worst investments so far: out of pure nostalgia I kept it for 15 years and at last sold for a 8 % profit. I made 3,45€. Luckily, I’ve made also better investments after that.

I like the thrill of catching a bargain and watching it’s value grow. Like the wreckage of an appartment on the far edge of Punavuori I was able to buy when I was 18 years old, which I completely renovated myself using something like 2000 euros and lived in for the years of seriously great afterparties. Since then, the most exclusive neighbourhood in Helsinki has been built right next to my old shady block, I've had only trustworthy tenants and getting a valuation for the place gives me a ridiculous amount of joy.  

It doesn’t have to be only stocks and funds and apartments though. Some of my best investments (in terms of hypothetical profit, to be honest these are things I would not part with) have been art works or furniture. One of my favorites: a very big floor lamp, on its way to the dumpster, which I carried home to my tiny first appartement and which turned out to be a super rare and passionately collected industrial lamp designed by the great Finnish designer Yrjö Kukkapuro.

## 8.3 Ballet
I’ve danced classical ballet since I was a kid. These days I dance on average six hours a week. Pirouettes are my specialty: I can’t lift my leg past my head or jump very high, but I can spin. Unfortunately, I have no data to back my claim. 

